---
# used for running tests
name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-22.04
    steps:
      # checks out the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch all history for all tags and branches
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Simulate version tag for cosmicqc install compatibility
        run: |
          git tag v99.0.0
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup for poetry
        run: |
          python -m pip install poetry
      - name: Install environment
        run: poetry install --no-interaction --no-ansi
      # run pre-commit
      - uses: pre-commit/action@v3.0.1
      # run pre-commit ci lite for automated fixes
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: ${{ !cancelled() }}
  run_tests:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-22.04, macos-14]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch all history for all tags and branches
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Simulate version tag for cosmicqc install compatibility
        run: |
          git tag v0.0.99
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup for poetry
        run: |
          python -m pip install poetry
      - name: Install environment
        run: poetry install --no-interaction --no-ansi
      - name: Run pytest
        # run all tests except those marked generate_report_image
        run: poetry run pytest -m "not generate_report_image"
